### ISSUE TITLE
Fails to pull back grooming tickets when there is no description

### ISSUE THREAD

**Issue by JasonHughes94** [bombadillo/point-it#1]
# Steps to reproduce

- Create a new Jira ticket with no description
- App will attempt to pull the tickets and fail with the following error

![image](https://user-images.githubusercontent.com/20440805/145194434-f9089757-bfed-45fd-bfe0-8c09cf2a3c65.png)

**Comment by bombadillo** [comment]
Fixed by https://github.com/bombadillo/point-it/commit/fe5f445851d60522648f8f518646c8059f36ebce.
